### PR TITLE
Enforce descriptive header in output files

### PR DESCRIPTION
**Pull request by abiddanda54gene**
Simple PR that adds the following features:

1. Adds headers to output files
2. Documents header and output filenames in `README.md`
3. updated dependency to default `unordered_map` vs. `tr1/unordered_map` for easier modern compilation. 

Any feedback / suggestions welcome.

### CODE REVIEW

**Comment by winni2k** [comment]
Thanks for the PR @abiddanda54gene! 

These changes look good. We will need to bump the version number to 1.0 due to the breaking interface changes, but i think it's been long enough since the last release.

Can you confirm that your contributions may be licensed under the MIT license? If so, please add a copyright line for yourself to the license file as part of this pr.

In the mean time, i will pull the proposed changes and make sure the tests still work. They do still pass, right?

**Comment by winni2k** [comment]
I now have the tests running in a github action. Please rebase onto master to get the tests running.

**Comment by abiddanda54gene** [comment]
Hi @winni2k - I've rebased onto master to get the CI routine. I think that adding the header made some of the tests break. I can address these in the next day or so. For the simple tests and checking by eye it seems that the values largely line up. 

Screen Shot 2022-02-22 at 9 46 02 AM

**Comment by winni2k** [comment]
If you could change the test data, then that would be great. I expect you will need to add the headers and replace spaces with tabs.

**Comment by abiddanda54gene** [comment]
@winni2k - just updated the tests and they pass locally on my Macbook. I think that you might need to approve that the workflow can run from my fork, but it should be good to merge.

**Comment by abiddanda54gene** [comment]
I'll also squash the commits down to streamline things a bit once this is approved.

**Comment by abiddanda54gene** [comment]
@winni2k - I think that this should be good to merge. Feel free to suggest changes in case they are necessary.

**Comment by abiddanda54gene** [comment]
I've changed the `nan` back to `-nan` in the predicted output (all other numbers are same) so tests should pass on CI now.

**Comment by winni2k** [comment]
This looks good! Thanks!

I'm not a lawyer, so i don't know if these changes are substantial enough to require a license from you. however, let's be careful. Could you please add a copyright line for your self to the license file?

Happy to merge after that.

**Comment by abiddanda54gene** [comment]
Awesome thanks @winni2k! I've just added a line to the previous license. I agree with all the previous licensing of the project so seems good on my end.

**Comment by abiddanda54gene** [comment]
HI @winni2k - I was hoping to make this into a `conda` package some point soon and would like to have the header in there if possible. Do let me know if there is anything outstanding w.r.t getting this PR merged in and I'd be happy to adjust code on my end as well. Thanks again!

**Comment by winni2k** [comment]
This looks great! Thanks for the bump. Will merge once the tests pass. It's quite annoying that the tests don't run right away...

**Pull request merged**
